databases:
  - name: attestli-demo-db
    plan: free
    databaseName: attestli
    user: attestli

services:
  - type: web
    name: attestli-demo
    runtime: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: attestli-demo-db
          property: connectionString
      - key: NODE_VERSION
        value: 20.18.0
